config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  resources :items, :orders, :menus
  
  get 'no_route' => 'errors#no_route'
  get 'record_not_found' => 'errors#record_not_found'
  get 'unauthorized' => 'errors#unauthorized'
  get 'users_only' => 'errors#users_only'
  
  root 'menus#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, inverse_of: :order
  has_many :items, through: :order_items
  
  accepts_nested_attributes_for :order_items
  
  validates :name,    presence: true, length: { in: 10..50 } 
  validates :address, presence: true, length: { in: 10..60 }
  validates :status,  presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create, :show]
  before_action :check_for_admin, only: [:new, :create, :show]
  
  def index
    @orders = Order.all
  end
  
  def new
    thank_you_page and return false unless params[:billed_order].blank?
    render 'new', locals: { ordered_items: ordered_items_list }
  end
  
  def create
    order = Order.create(order_params)
    order = count_totals(order)
    redirect_to new_order_path(billed_order: order.id) and return if order.save
    redirect_to session.delete(:return_to)
  end
  
  def show
    respond_to_format(:pdf, :generate_pdf)
  end
  
  def update
    order = Order.find_by_id(params[:id])
    respond_to_format(:json, :json_success) if order.update(order_update_params)
  end
  
  private
  
  def check_for_admin
    redirect_to users_only_path if current_admin
  end
  
  def count_totals obj
    total = 0
    obj.order_items.each {|i| total = update_order_item(i, total) }
    obj.update(total: total, status: 'Confirmed')
    obj
  end
  
  def find_items item_ids
    items = []
    item_ids.split(',').each { |id| items << Item.find_by_id(id) }
    items
  end
  
  def generate_pdf 
    order = Order.find_by_id(params[:id])
    pdf = BillGenerator.new(order).run
    send_data pdf.render, filename: "bill_#{order.id}.pdf", type: 'application/pdf'
  end
  
  def json_success
    render json: { status: 200 }
  end
  
  def order_params
    params.require(:order).permit(:name, 
                                  :address, 
                                  :email, 
                                  order_items_attributes: [:item_id, :amount])
  end
  
  def order_update_params
    params.require(:order).permit(:status)
  end
  
  def ordered_items_list
    return find_items(params[:items_ids]) unless params[:items_ids].blank?
    nil
  end
  
  def respond_to_format frmt, actn
    respond_to do |format| 
      format.html 
      format.send(frmt) { self.send(actn) }
    end
  end
  
  def thank_you_page
    render 'thank_you', locals: { billed_order: params[:billed_order] }
  end
  
  def update_order_item obj, total
    sum = obj.amount * obj.item.price
    obj.update(total: sum) 
    return total + sum
  end
end

app/views/orders/index.html.erb
<h1>All orders:</h1>

<div class='orders-table-wrapper'>
  <table class='orders'>
    <tr>
      <th>Order #</th>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Sum</th>
      <th>Details</th>
      <th>Status</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.total %></td>
        <td class='order-details flex'>
          <% order.order_items.each do |item| %>
            <div class='order-item-img' data="<%= item.id %>">
              <%= cl_image_tag item.item.image %>
            </div>
            <span class='order-item-details hidden' data="<%= item.id %>" >
              <div class='order-item-title'><%= item.item.title %></div>
              <div class='order-item-amount'><%= item.amount %></div>
            </span>
          <% end %>
        </td>
        <td class='order-status' data="<%= order.id %>">
          <div class='order-status-current'><%= order.status %></div>
          <div class='order-statuses hidden'>
            <input class='order-status-radio' type='radio' name='status' value='Confirmed'> Confirmed</br>
            <input class='order-status-radio' type='radio' name='status' value='Being processed'> Being processed</br>
            <input class='order-status-radio' type='radio' name='status' value='Delivered'> Delivered
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/new.html.erb
<h1>Order preview:</h1>

<form class='order-form' action='/orders' method='POST'>
  
  <input name='authenticity_token' type='hidden' 
         value="<%= form_authenticity_token %>" />
         
  <div class='order form-element'>
    <% if ordered_items %>
      <label>Ordered items:</label>
      <div class='ordered-items-table-wrapper'>
        <table class='order-items'>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Calories for one</th>
            <th>Price for one</th>
            <th>Amount</th>
          </tr>
          <% ordered_items.each do |item| %>
            <tr>
              <td>
                <input type='text' class='ordered-item hidden' name='order[order_items_attributes][][item_id]' value='<%= item.id %>' />
              </td>
              <td><%= item.title %></td>
              <td><%= item.calorie %></td>
              <td class='ordered-item-price'><%= item.price %></td>
              <td>
                <input type='text' class='ordered-amount' name='order[order_items_attributes][][amount]' value='1' />
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <label>No items have been ordered!</label>
    <% end %>
  </div>
  
  <div class='order form-element flex'>
    <p class='total-sum-of-ordered-items'></p>
  </div>

  <div class='order form-element flex'>
    <label class='item-label order-new'>Full name:</label>
    <div class='order-input-type name'>
      <input type='text' name='order[name]' id='order-input-type-name' />
      <p class='validation'>This field is required!</p>
    </div>
  </div>
  
  <div class='order form-element flex'>
    <label class='item-label order-new'>Delivery address:</label>
    <div class='order-input-type address'>
      <input type='text' name='order[address]' id='order-input-type-address' />
      <p class='validation'>This field is required!</p>
    </div>
  </div>
  
  <div class='order form-element flex'>
    <label class='item-label order-new'>Email:</label>
    <div class='order-input-type'>
      <input type='text' name='order[email]' />
    </div>
  </div>
  
  <div class='order form-element flex btn-add-order-wrapper'>
    <div class='btn-add-order'>
      <input type='submit' value='Place order' class='btn add-order' />
    </div>
  </div>
</form>

app/views/orders/thank_you.html.erb
<h1>Your order was successfully created!</h1>
<div class='thank-you'>
  <p class='get-pdf'>To get PDF version of your bill press the following button:</p>
  <div class='btn-wrapper flex'>
    <div class='btn download-bill'>
      <%= link_to 'Get Bill!', order_path(id: billed_order, format: 'pdf'), 
                  class: '' %>
    </div>
  </div>
</div>