config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  resources :items, :orders, :menus
  
  get 'no_route' => 'errors#no_route'
  get 'record_not_found' => 'errors#record_not_found'
  get 'unauthorized' => 'errors#unauthorized'
  get 'users_only' => 'errors#users_only'
  
  root 'menus#index'
end

app/models/concerns/item_type.rb
require 'active_support/concern'

module ItemType
  extend ActiveSupport::Concern
  included do
    def self.types
      {
         FC: 'First course', MC: 'Main course', DR: 'Drink'
      }.freeze
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include ItemType
  has_many :order_items
  has_many :orders, through: :order_items
  has_and_belongs_to_many :menus
  
  mount_uploader :image, ImageUploader
  
  validates :item_type, presence: true
  validates :title,     presence: true, length: { in: 4..60 }, uniqueness: true
  validates :price,     presence: true, numericality: { only_float: true }
  
  paginates_per 4
  
  scope :first_courses, -> { where(item_type: 'First course') }
  scope :main_courses, ->  { where(item_type: 'Main course') }
  scope :drinks, ->        { where(item_type: 'Drink') }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]

  def new
    new_or_edit 'new'
  end
  
  def create
    item = Item.new(item_params)
    redirect_to items_path and return false if item.save
  	redirect_to session.delete(:return_to)
  end
  
  def index
    render 'index', locals: { items: Item.all.page(params[:page]) }
  end
  
  def edit
    new_or_edit('edit', Item.find(params[:id]))
  end
  
  def update
    item = Item.find_by_id(params[:id])
    redirect_to items_path and return false if item.update(item_params)
    redirect_to session.delete(:return_to)
  end
  
  def destroy
    item = Item.find_by_id(params[:id])
    item.destroy if item
    redirect_to items_path
  end

  private
  
  def new_or_edit(page, item = nil)
   render page, locals: { types: Item.types.values, 
                          item: item ? item : Item.new }
  end

  def item_params
  	params.require(:item).permit(:item_type, 
  	                             :title, 
  	                             :price, 
  	                             :description, 
  	                             :fat, 
  	                             :carbohydrate,
  	                             :protein, 
  	                             :calorie, 
  	                             :image)
  end
end

app/views/items/_form.html.erb
<%= simple_form_for item, html: { multipart: true } do |f| %>
  <div class='item-field'>
    <%= f.input :item_type, as: :radio_buttons, collection: types %>
    <p class='validation-item'>This field is required!</p>
  </div>
  
  <div class='item-field'>
    <%= f.input :title %>
    <p class='validation-item'>This field is required!</p>
  </div>
  
  <div class='item-field'>
    <%= f.input :price %>
    <p class='validation-item'>This field is required!</p>
  </div>
  
  <div class='item-field'>
    <%= f.input :fat %>
  </div>
  
  <div class='item-field'>
    <%= f.input :carbohydrate %>
  </div>
  
  <div class='item-field'>
    <%= f.input :protein %>
  </div>
  
  <div class='item-field'>
    <%= f.input :calorie %>
  </div>
  
  <div class='item-field'>
    <%= f.input :description %>
  </div>
  
  <div class='item-field img'>
    <% if image %>
      <%= cl_image_tag image %>
    <% end %>
  </div>
  
  <div class='item-field'>
    <%= f.input :image %>
  </div>
  
  <div class='item-submit-btn-wrapper'>
    <div class='btn'>
      <%= f.submit "#{action}"%>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class='item-form'>
  <h1>Edit item:</h1>
  <%= render partial: 'items/form', locals: { item: item, 
                                              types: types, 
                                              image: item.image,
                                              action: 'Edit' } %>  
</div>

app/views/items/index.html.erb
<h1>All menu items:</h1>

<% items.each do |item| %>
  <ul class='items wth-border'>
    <li class='items flex element'>
      <div class='items element-img'>
        <%= cl_image_tag item.image_url.to_s, class: 'wth-border' %>
      </div>
      <div class='items element-details'>
        <div class='items element-details title'>
          <%= item.title %>
        </div>
        <div class='items element-details price'>
          <%= item.price %>
        </div>
      </div>
      <% if current_admin %>
        <div class='items element-admin-panel'>
          <%= button_to "Edit", { action: "edit", id: item.id }, 
              method: :get, class: 'btn' %>
          <%= button_to "Delete", { action: "destroy", id: item.id }, 
              method: :delete, class: 'btn' %>
        </div>
      <% end %>
    </li>
  </ul>
<% end %>

<div class='pagination-bar'>
  <%= paginate items, :window => 2, :outer_window => 1 %>
</div>

app/views/items/new.html.erb
<div class='item-form'>
  <h1>Add item:</h1>
  <%= render partial: 'items/form', locals: { item: item, 
                                              types: types, 
                                              image: nil,
                                              action: 'Add' } %>  
</div>