config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  resources :items, :orders, :menus
  
  get 'no_route' => 'errors#no_route'
  get 'record_not_found' => 'errors#record_not_found'
  get 'unauthorized' => 'errors#unauthorized'
  get 'users_only' => 'errors#users_only'
  
  root 'menus#index'
end

app/views/layouts/_footer.html.erb
<div class='footer'>
  <p>Header images <a href="http://www.freepik.com">designed by Freepik</a></p>  
  <p>&copy; LunchApp, 2017</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta charset="utf-8"/>
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title>
      <%= content_for?(:title) ? yield(:title) : "LunchApp" %>
    </title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  
  <body>
    <div class='content-wrapper flex'>
      <div class='sidebar'>
        <div class='sidebar-icon-wrapper'><div class='sidebar-icon'></div></div>
        <ul class='sidebar-items'>
          <li class='sidebar-item-close'><p>X</p></li>
          <li class='sidebar-item'><%= link_to 'Home', menus_path %></li>
          <li class='sidebar-item'><%= link_to 'All meals', items_path %></li>
          <% if signed_in? %>
            <li class='sidebar-item'><%= link_to 'Orders', orders_path %></li>
            <li class='sidebar-item'><%= link_to 'New meal', new_item_path %></li>
            <li class='sidebar-item'><%= link_to 'New menu', new_menu_path %></li>
            <li class='sidebar-item'><%= link_to 'Sign out', 
                                         destroy_admin_session_path, 
                                         method: 'delete' %></li>
          <% else %>
            <li class='sidebar-item order-preview-form hidden'><a href='#'>Preview order</a></li>
            <li class='sidebar-item admin-login'><a href='#'>Admin</a></li>
            <li class='admin-login-form hidden'>
              <div class='admin-login-form-wrapper'>
                <div class='admin-login-form-el-wrapper'>
                  <label class='admin-login-label'>Email:</label>
                </div>
                <div class='admin-login-form-el-wrapper'>
                  <input type='text' class='admin-login-input email' />
                </div>
                <div class='admin-login-form-el-wrapper'>
                  <label class='admin-login-label'>Password:</label>
                </div>
                <div class='admin-login-form-el-wrapper'>
                  <input type='password' class='admin-login-input password' />
                </div>
                <div class='admin-login-btn'>
                  <div class='btn admin-login'>
                    <input type='submit' value='Login' class='login' />
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      
      <div class='content'>
        <div class='header flex'>
          <div class='header-img-wrapper'>
            <div class='header-img wth-border' id='img-burger'></div>
          </div>
          <div class='header-img-wrapper'>
            <div class='header-img wth-border' id='img-eggs'></div>
          </div>
          <div class='header-img-wrapper'>
            <div class='header-img wth-border' id='img-pizza'></div>
          </div>
          <div class='header-img-wrapper'>
            <div class='header-img wth-border' id='img-sweets'></div>
          </div>
        </div>
        
        <div class='main'>
          <%= yield %>
        </div>
        
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>